INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (0, 'Antoine', 'Davis', 'Detroit Mercy (Horiz');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (1, 'Jordan', 'Dingle', 'Penn (Ivy League)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (2, 'Darius', 'McGhee', 'Liberty (ASUN)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (3, 'Elijah', 'Pepper', 'UC Davis (Big West)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (4, 'Jordan', 'Walker', 'UAB (C-USA)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (5, 'Zach', 'Edey', 'Purdue (Big Ten)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (6, 'Taevion', 'Kinsey', 'Marshall (Sun Belt)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (7, 'Kendric', 'Davis', 'Memphis (AAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (8, 'Max', 'Abmas', 'Oral Roberts (Summit');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (9, 'Josh', 'Cohen', 'Saint Francis (PA) (');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (10, 'Xavier', 'Castaneda', 'Akron (MAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (11, 'James', 'Bishop', 'George Washington (A');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (12, 'Cam', 'Shelton', 'LMU (CA) (WCC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (13, 'Drew', 'Timme', 'Gonzaga (WCC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (14, 'Drew', 'Pember', 'UNC Asheville (Big S');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (15, 'Trayce', 'Jackson-Davis', 'Indiana (Big Ten)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (16, 'Jameer', 'Nelso', 'Delaware (CAA)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (17, 'Sam', 'Sessoms', 'Coppin St. (MEAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (18, 'Trey', 'Calvin', 'Wright St. (Horizon)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (19, 'Justin', 'Johnson', 'UTRGV (WAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (20, 'Kris', 'Murray', 'Iowa (Big Ten)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (21, 'Aaron', 'Estrada', 'Hofstra (CAA)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (22, 'Dalton', 'Knecht', 'Northern Colo. (Big ');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (23, 'Andrew', 'Taylor', 'Marshall (Sun Belt)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (24, 'Denver', 'Jones', 'FIU (C-USA)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (25, 'Jalen', 'Wilson', 'Kansas (Big 12)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (26, 'Jalen', 'Cook', 'Tulane (AAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (27, 'Brandin', 'Podziemski', 'Santa Clara (WCC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (28, 'Azuolas', 'Tubelis', 'Arizona (Pac-12)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (29, 'Erik', 'Reynold', 'Saint Josephs (Atlan');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (30, 'Jalen', 'Moore', 'Oakland (Horizon)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (31, 'Demarcus', 'Sharp', 'Northwestern St. (So');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (32, 'RayJ', 'Dennis', 'Toledo (MAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (33, 'Noah', 'Thomasson', 'Niagara (MAAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (34, 'Ben', 'Krikke', 'Valparaiso (MVC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (35, 'Isaac', 'Jones', 'Idaho (Big Sky)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (36, 'Jr.', 'Clay', 'Tennessee St. (OVC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (37, 'Jordan', 'Brown', 'Louisiana (Sun Belt)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (38, 'Emoni', 'Bates', 'Eastern Mich. (MAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (39, 'Jamal', 'Mashburn', 'Jr.');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (40, 'Patrick', 'Gardner', 'Marist (MAAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (41, 'Elijah', 'Harkless', 'UNLV (Mountain West)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (42, 'Tyler', 'Burton', 'Richmond (Atlantic 1');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (43, 'Trenton', 'Massner', 'Western Ill. (Summit');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (44, 'Isaiah', 'Moore', 'South Alabama (Sun B');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (45, 'Tyree', 'Appleby', 'Wake Forest (ACC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (46, 'Ben', 'Sheppard', 'Belmont (MVC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (47, 'Marques', 'Warrick', 'Northern Ky. (Horizo');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (48, 'Chris', 'Ledlum', 'Harvard (Ivy League)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (49, 'Brandon', 'Miller', 'Alabama (SEC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (50, 'Quincy', 'Olivari', 'Rice (C-USA)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (51, 'Isaiah', 'Burke', 'Morgan St. (MEAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (52, 'Cameron', 'Tyson', 'Seattle U (WAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (53, 'Tucker', 'DeVries', 'Drake (MVC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (54, 'Hunter', 'Dickinson', 'Michigan (Big Ten)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (55, 'Jaylen', 'Forbes', 'Tulane (AAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (56, 'DaRon', 'Holme', 'Dayton (Atlantic 10)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (57, 'Zyon', 'Pullin', 'UC Riverside (Big We');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (58, 'Divante', 'Moffitt', 'Idaho (Big Sky)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (59, 'Zeke', 'Mayo', 'South Dakota St. (Su');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (60, 'BJ', 'Freeman', 'Milwaukee (Horizon)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (61, 'Cameron', 'Parker', 'Portland St. (Big Sk');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (62, 'Phillip', 'Russell', 'Southeast Mo. St. (O');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (63, 'Jordan', 'Johnson', 'New Orleans (Southla');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (64, 'Dwayne', 'Cohill', 'Youngstown St. (Hori');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (65, 'Terquavion', 'Smith', 'NC State (ACC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (66, 'Khalif', 'Battle', 'Temple (AAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (67, 'Bowen', 'Born', 'UNI (MVC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (68, 'Isaiah', 'Stevens', 'Colorado St. (Mounta');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (69, 'Grant', 'Nelson', 'North Dakota St. (Su');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (70, 'Mike', 'Miles', 'TCU (Big 12)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (71, 'Jaime', 'Jaque', 'UCLA (Pac-12)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (72, 'Khalil', 'Shabazz', 'San Francisco (WCC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (73, 'Ray', 'Harrison', 'Grand Canyon (WAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (74, 'Jarred', 'Godfrey', 'Purdue Fort Wayne (H');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (75, 'Tevian', 'Jones', 'Southern Utah (WAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (76, 'Joe', 'Bryant', 'Norfolk St. (MEAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (77, 'Jalen', 'Pickett', 'Penn St. (Big Ten)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (78, 'Keion', 'Brook', 'Washington (Pac-12)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (79, 'Nicolas', 'Timberlake', 'Towson (CAA)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (80, 'Mike', 'Bothwell', 'Furman (SoCon)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (81, 'RaeQuan', 'Battle', 'Montana St. (Big Sky');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (82, 'DeAndre', 'Williams', 'Memphis (AAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (83, 'Shaun', 'Dos', 'Ark.-Pine Bluff (SWA');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (84, 'Boogie', 'Ellis', 'Southern California ');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (85, 'Jacob', 'Ognacevic', 'Lipscomb (ASUN)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (86, 'KJ', 'Williams', 'LSU (SEC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (87, 'El', 'Ellis', 'Louisville (ACC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (88, 'Nate', 'Calmese', 'Lamar University (So');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (89, 'Markquis', 'Nowell', 'Kansas St. (Big 12)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (90, 'Jalen', 'Cone', 'Northern Ariz. (Big ');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (91, 'Sincere', 'Carry', 'Kent St. (MAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (92, 'Zhuric', 'Phelps', 'SMU (AAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (93, 'Keyontae', 'Johnson', 'Kansas St. (Big 12)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (94, 'Brendan', 'Adams', 'George Washington (A');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (95, 'Omari', 'Moore', 'San Jose St. (Mounta');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (96, 'Claudell', 'Harri', 'Charleston So. (Big ');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (97, 'Tylor', 'Perry', 'North Texas (C-USA)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (98, 'Lamar', 'Norma', 'Western Mich. (MAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (99, 'Boo', 'Buie', 'Northwestern (Big Te');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (100, 'Kam', '', 'N.C. AT (CAA)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (101, 'RayQuawndis', 'Mitchell', 'Kansas City (Summit ');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (102, 'Marcellus', 'Earlington', 'San Diego (WCC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (103, 'Jaden', 'House', 'High Point (Big Sout');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (104, 'Daylen', 'Kountz', 'Northern Colo. (Big ');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (105, 'Mekhi', 'Lairy', 'Miami (OH) (MAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (106, 'Terrence', 'Shanno', 'Illinois (Big Ten)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (107, 'Adama', 'Sanogo', 'UConn (Big East)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (108, 'Sherif', 'Gross-Bullock', 'Bryant (America East');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (109, 'Maxwell', 'Lewis', 'Pepperdine (WCC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (110, 'Jarkel', 'Joiner', 'NC State (ACC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (111, 'Shemarri', 'Allen', 'Kansas City (Summit ');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (112, 'Jarod', 'Lucas', 'Nevada (Mountain Wes');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (113, 'Jaelen', 'House', 'New Mexico (Mountain');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (114, 'Devontae', 'Blanton', 'Eastern Ky. (ASUN)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (115, 'Tyler', 'Harris', 'South Fla. (AAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (116, 'Darius', 'Quisenberry', 'Fordham (Atlantic 10');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (117, 'Camren', 'Hunter', 'Central Ark. (ASUN)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (118, 'Kino', 'Lill', 'Brown (Ivy League)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (119, 'Landers', 'Nolle', 'Cincinnati (AAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (120, 'Enrique', 'Freeman', 'Akron (MAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (121, 'Walter', 'Clayto', 'Iona (MAAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (122, 'Marcus', 'Sasser', 'Houston (AAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (123, 'Atin', 'Wright', 'CSUN (Big West)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (124, 'Marcus', 'Domask', 'Southern Ill. (MVC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (125, 'Caleb', 'Love', 'North Carolina (ACC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (126, 'Dillon', 'Jones', 'Weber St. (Big Sky)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (127, 'Wesley', 'Cardet', 'Chicago St. (DI Inde');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (128, 'Jonathan', 'Cisse', 'UIW (Southland)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (129, 'Jalen', 'Rucker', 'Army West Point (Pat');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (130, 'Demetre', 'Roberts', 'FDU (NEC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (131, 'Jace', 'Carter', 'UIC (MVC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (132, 'B.J.', 'Mack', 'Wofford (SoCon)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (133, 'Leon', 'Ayer', 'Bowling Green (MAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (134, 'Tyler', 'Thomas', 'Hofstra (CAA)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (135, 'Trey', 'Townsend', 'Oakland (Horizon)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (136, 'Dayvion', 'McKnight', 'Western Ky. (C-USA)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (137, 'Carter', 'Hendricksen', 'North Florida (ASUN)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (138, 'Caleb', 'Huffman', 'Nicholls (Southland)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (139, 'Oscar', 'Tshiebwe', 'Kentucky (SEC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (140, 'Joseph', 'Girar', 'Syracuse (ACC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (141, 'Ishmael', 'Leggett', 'Rhode Island (Atlant');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (142, 'Grant', 'Basile', 'Virginia Tech (ACC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (143, 'Morris', 'Udeze', 'New Mexico (Mountain');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (144, 'Jahmyl', 'Telfort', 'Northeastern (CAA)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (145, 'Branden', 'Carlson', 'Utah (Pac-12)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (146, 'Souley', 'Boum', 'Xavier (Big East)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (147, 'Wade', 'Taylo', 'Texas AM (SEC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (148, 'Latrell', 'Wrightsel', 'Cal St. Fullerton (B');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (149, 'Ajay', 'Mitchell', 'UC Santa Barbara (Bi');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (150, 'Stephen', 'Clark', 'The Citadel (SoCon)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (151, 'Judah', 'Mintz', 'Syracuse (ACC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (152, 'Brice', 'Sensabaugh', 'Ohio St. (Big Ten)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (153, 'Foster', 'Loyer', 'Davidson (Atlantic 1');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (154, 'Tyrell', 'Roberts', 'San Francisco (WCC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (155, 'Kelton', 'Talford', 'Winthrop (Big South)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (156, 'Steven', 'Ashworth', 'Utah St. (Mountain W');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (157, 'Kobe', 'King', 'Valparaiso (MVC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (158, 'Jordan', 'Hawkins', 'UConn (Big East)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (159, 'Isaiah', 'Wong', 'Miami (FL) (ACC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (160, 'Ricky', 'Counci', 'Arkansas (SEC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (161, 'Gerrale', 'Gates', 'Holy Cross (Patriot)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (162, 'RJ', 'Davis', 'North Carolina (ACC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (163, 'Setric', 'Millne', 'Toledo (MAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (164, 'Parker', 'Stewart', 'UT Martin (OVC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (165, 'Justin', 'Wright', 'N.C. Central (MEAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (166, 'Aanen', 'Moody', 'Montana (Big Sky)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (167, 'Jalen', 'Benjamin', 'Mount St. Marys (MAA');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (168, 'JT', 'Shumate', 'Toledo (MAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (169, 'Austin', 'Crowley', 'Southern Miss. (Sun ');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (170, 'Primo', 'Spears', 'Georgetown (Big East');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (171, 'Colin', 'Castleton', 'Florida (SEC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (172, 'Marko', 'Maletic', 'LIU (NEC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (173, 'Ryan', 'Kalkbrenner', 'Creighton (Big East)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (174, 'Armando', 'Bacot', 'North Carolina (ACC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (175, 'Mason', 'Harrell', 'Texas St. (Sun Belt)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (176, 'Javian', 'McCollum', 'Siena (MAAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (177, 'Courvoisier', 'McCauley', 'Indiana St. (MVC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (178, 'Tristan', 'd', 'Colorado (Pac-12)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (179, 'Tommy', 'Bruner', 'Denver (Summit Leagu');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (180, 'Grant', 'Sherfield', 'Oklahoma (Big 12)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (181, 'Marcus', 'Carr', 'Texas (Big 12)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (182, 'KJ', 'Simpson', 'Colorado (Pac-12)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (183, 'Umoja', 'Gibson', 'DePaul (Big East)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (184, 'Kobe', 'Brown', 'Missouri (SEC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (185, 'Tre', 'Jackson', 'Western Caro. (SoCon');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (186, 'TJ', 'Bamba', 'Washington St. (Pac-');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (187, 'Jahmir', 'Young', 'Maryland (Big Ten)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (188, 'Bryce', 'Hopkins', 'Providence (Big East');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (189, 'Trevian', 'Tennyson', 'AM-Corpus Christi (S');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (190, 'Gerald', 'Drumgool', 'UAlbany (America Eas');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (191, 'Tolu', 'Smith', 'Mississippi St. (SEC');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (192, 'Khalid', 'Moore', 'Fordham (Atlantic 10');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (193, 'Dwight', 'Murray', 'Jr.');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (194, 'Tyler', 'Robertson', 'Portland (WCC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (195, 'Josh', 'Oduro', 'George Mason (Atlant');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (196, 'Travis', 'Evee', 'Rice (C-USA)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (197, 'Daniss', 'Jenkins', 'Iona (MAAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (198, 'Adam', 'Flagler', 'Baylor (Big 12)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (199, 'Jalen', 'Slawson', 'Furman (SoCon)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (200, 'Tristan', 'Enaruna', 'Cleveland St. (Horiz');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (201, 'Chris', 'Harris', 'Southeast Mo. St. (O');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (202, 'Jordan', 'King', 'ETSU (SoCon)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (203, 'Hunter', 'Maldonado', 'Wyoming (Mountain We');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (204, 'Kahliel', 'Spear', 'Robert Morris (Horiz');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (205, 'Dae', 'Da', 'Duquesne (Atlantic 1');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (206, 'David', 'Coit', 'NIU (MAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (207, 'RaySean', 'Taylor', 'SIUE (OVC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (208, 'Morgan', 'Safford', 'Miami (OH) (MAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (209, 'Eric', 'Dixon', 'Villanova (Big East)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (210, 'JaMonta', 'Black', 'Northwestern St. (So');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (211, 'Dwight', 'Wilson', 'Ohio (MAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (212, 'Jaylen', 'Sebree', 'Tennessee Tech (OVC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (213, 'Jalen', 'Blackmon', 'Stetson (ASUN)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (214, 'Enoch', 'Cheeks', 'Robert Morris (Horiz');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (215, 'Gregory', '"GG', 'South Carolina (SEC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (216, 'Daryl', 'Bank', 'St. Bonaventure (Atl');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (217, 'Gedi', 'Juozapaitis', 'Maine (America East)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (218, 'Nico', 'Galette', 'Sacred Heart (NEC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (219, 'Tyzhaun', 'Claude', 'Western Caro. (SoCon');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (220, 'Erik', 'Stevenson', 'West Virginia (Big 1');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (221, 'Dawson', 'Baker', 'UC Irvine (Big West)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (222, 'Keyonte', 'George', 'Baylor (Big 12)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (223, 'Moses', 'Wood', 'Portland (WCC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (224, 'Dawson', 'Garcia', 'Minnesota (Big Ten)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (225, 'PJ', 'Hall', 'Clemson (ACC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (226, 'Clarence', 'Daniels', 'New Hampshire (Ameri');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (227, 'Jordan', 'Miller', 'Miami (FL) (ACC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (228, 'Hunter', 'Tyson', 'Clemson (ACC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (229, 'Jyare', 'Davis', 'Delaware (CAA)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (230, 'Demaree', 'King', 'Jacksonville St. (AS');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (231, 'Jordan', 'Sears', 'UT Martin (OVC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (232, 'Blake', 'Hinson', 'Pittsburgh (ACC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (233, 'Steele', 'Venters', 'Eastern Wash. (Big S');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (234, 'Damian', 'Dunn', 'Temple (AAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (235, 'Julian', 'Strawther', 'Gonzaga (WCC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (236, 'Joel', 'Soriano', 'St. Johns (NY) (Big ');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (237, 'Jamarius', 'Burton', 'Pittsburgh (ACC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (238, 'Jordan', 'Gainey', 'USC Upstate (Big Sou');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (239, 'Austin', 'Ash', 'The Citadel (SoCon)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (240, 'Sam', 'Griffin', 'Tulsa (AAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (241, 'Terry', 'Collins', 'Mississippi Val. (SW');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (242, 'Sam', 'Mennenga', 'Davidson (Atlantic 1');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (243, 'Jalyn', 'McCreary', 'Mercer (SoCon)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (244, 'Carlos', 'Stewart', 'Santa Clara (WCC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (245, 'Taylor', 'Hendricks', 'UCF (AAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (246, 'Ant', 'Nelson', 'Manhattan (MAAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (247, 'Boden', 'Skunberg', 'North Dakota St. (Su');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (248, 'Jake', 'Heidbreder', 'Air Force (Mountain ');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (249, 'Kyle', 'Filipowski', 'Duke (ACC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (250, 'Tosan', 'Evbuomwan', 'Princeton (Ivy Leagu');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (251, 'Jackson', 'Paveletzke', 'Wofford (SoCon)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (252, 'Christian', 'Shumate', 'McNeese (Southland)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (253, 'Kam', 'Jones', 'Marquette (Big East)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (254, 'Josh', 'Bannan', 'Montana (Big Sky)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (255, 'Will', 'Douglas', 'Prairie View (SWAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (256, 'Curtis', 'Jones', 'Buffalo (MAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (257, 'Eddy', 'Kayouloud', 'Central Ark. (ASUN)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (258, 'Colby', 'Jones', 'Xavier (Big East)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (259, 'DJ', 'Davis', 'UC Irvine (Big West)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (260, 'Sean', 'Pedulla', 'Virginia Tech (ACC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (261, 'Felipe', 'Haase', 'Southern Miss. (Sun ');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (262, 'LJ', 'Cryer', 'Baylor (Big 12)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (263, 'Maks', 'Klanjscek', 'Houston Christian (S');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (264, 'Latrell', 'Jones', 'Nicholls (Southland)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (265, 'Mark', 'Freeman', 'Morehead St. (OVC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (266, 'Jase', 'Townsend', 'San Diego (WCC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (267, 'Jordan', 'Nesbitt', 'Hampton (CAA)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (268, 'Isaiah', 'Thompson', 'FGCU (ASUN)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (269, 'Paxson', 'Wojcik', 'Brown (Ivy League)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (270, 'Tajion', 'Jones', 'UNC Asheville (Big S');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (271, 'Nelly', 'Joseph', 'Iona (MAAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (272, 'David', 'DeJulius', 'Cincinnati (AAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (273, 'Kevin', 'Cross', 'Tulane (AAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (274, 'Tyson', 'Walker', 'Michigan St. (Big Te');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (275, 'Daniel', 'Ortiz', 'North Ala. (ASUN)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (276, 'KJ', 'Simon', 'UT Martin (OVC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (277, 'Brycen', 'Long', 'Houston Christian (S');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (278, 'Walter', 'Whyte', 'Boston U. (Patriot)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (279, 'DMoi', 'Hodge', 'Missouri (SEC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (280, 'Keith', 'Higgin', 'Lehigh (Patriot)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (281, 'Chris', 'Youngblood', 'Kennesaw St. (ASUN)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (282, 'Frankie', 'Fidler', 'Omaha (Summit League');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (283, 'Charles', 'Pride', 'Bryant (America East');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (284, 'Philip', 'Alston', 'Loyola Chicago (Atla');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (285, 'John', 'Tonje', 'Colorado St. (Mounta');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (286, 'Jalen', 'Haynes', 'ETSU (SoCon)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (287, 'Jlynn', 'Counter', 'IUPUI (Horizon)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (288, 'Ty', 'Johnson', 'UC Davis (Big West)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (289, 'Will', 'Johnston', 'UTRGV (WAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (290, 'Isaac', 'Mushila', 'AM-Corpus Christi (S');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (291, 'Vonterius', 'Woolbright', 'Western Caro. (SoCon');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (292, 'Jesse', 'Edwards', 'Syracuse (ACC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (293, 'Cameron', 'Holden', 'Towson (CAA)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (294, 'Logan', 'Johnson', 'Saint Marys (CA) (WC');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (295, 'Briggs', 'McClain', 'Hartford (DI Indepen');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (296, 'Tyreke', 'Locure', 'ULM (Sun Belt)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (297, 'Matthew', 'Murrell', 'Ole Miss (SEC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (298, 'Miles', 'Kelly', 'Georgia Tech (ACC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (299, 'Joey', 'Hauser', 'Michigan St. (Big Te');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (300, 'Kevin', 'Obanor', 'Texas Tech (Big 12)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (301, 'Kinyon', 'Hodges', 'Eastern Ill. (OVC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (302, 'Rob', 'Perry', 'Murray St. (MVC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (303, 'Kenny', 'Strawbridge', 'Evansville (MVC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (304, 'Brian', 'Taylor', 'Central Mich. (MAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (305, 'Antonio', 'Reeves', 'Kentucky (SEC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (306, 'Keyshaun', 'Langley', 'UNC Greensboro (SoCo');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (307, 'Jarron', 'Coleman', 'Ball St. (MAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (308, 'Tyler', 'Stephenson-Moore', 'Stony Brook (CAA)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (309, 'Kellen', 'Tynes', 'Maine (America East)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (310, 'Khalil', 'Brantley', 'La Salle (Atlantic 1');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (311, 'Mouhamed', 'Gueye', 'Washington St. (Pac-');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (312, 'Damarco', 'Minor', 'SIUE (OVC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (313, 'Anderson', 'Mirambeaux', 'Miami (OH) (MAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (314, 'Andrei', 'Savrasov', 'Ga. Southern (Sun Be');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (315, 'Tyson', 'Acuff', 'Eastern Mich. (MAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (316, 'Kruz', 'Perrott-Hunt', 'South Dakota (Summit');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (317, 'Boogie', 'Anderson', 'Southeastern La. (So');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (318, 'Javan', 'Johnson', 'DePaul (Big East)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (319, 'Kris', 'Bankston', 'Norfolk St. (MEAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (320, 'Jett', 'Howard', 'Michigan (Big Ten)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (321, 'Trazarien', 'White', 'UNCW (CAA)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (322, 'Asher', 'Woods', 'VMI (SoCon)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (323, 'Ricky', 'Clemons', 'Campbell (Big South)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (324, 'Caleb', 'Daniels', 'Villanova (Big East)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (325, 'Qua', 'Grant', 'Sam Houston (WAC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (326, 'Oumar', 'Ballo', 'Arizona (Pac-12)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (327, 'Seth', 'Lundy', 'Penn St. (Big Ten)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (328, 'Evan', 'Taylor', 'Lehigh (Patriot)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (329, 'Jack', 'Nunge', 'Xavier (Big East)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (330, 'Jahsean', 'Corbett', 'Chicago St. (DI Inde');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (331, 'Skyelar', 'Potter', 'Jacksonville St. (AS');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (332, 'Marcus', 'Watson', 'N.C. AT (CAA)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (333, 'Johni', 'Broome', 'Auburn (SEC)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (334, 'Tyson', 'Degenhart', 'Boise St. (Mountain ');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (335, 'Marcus', 'Tsohonis', 'Long Beach St. (Big ');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (336, 'Xander', 'Rice', 'Bucknell (Patriot)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (337, 'Matt', 'Rogers', 'American (Patriot)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (338, 'Miles', 'Norris', 'UC Santa Barbara (Bi');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (339, 'Zach', 'Austin', 'High Point (Big Sout');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (340, 'Kellen', 'Amos', 'Central Conn. St. (N');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (341, 'Kenan', 'Blackshear', 'Nevada (Mountain Wes');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (342, 'Gradey', 'Dick', 'Kansas (Big 12)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (343, 'Spencer', 'Jones', 'Stanford (Pac-12)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (344, 'Filip', 'Rebraca', 'Iowa (Big Ten)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (345, 'Chase', 'Audige', 'Northwestern (Big Te');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (346, 'Max', 'Rice', 'Boise St. (Mountain ');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (347, 'Kobe', 'Bufkin', 'Michigan (Big Ten)');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (348, 'Gibson', 'Jimerson', 'Saint Louis (Atlanti');
INSERT INTO COLLEGE_PLAYERS(PlayerID, FirstName, LastName, University) VALUES (349, 'Jordan', 'Henderson', 'Canisius (MAAC)');
